slack:
  channel: "#drawma"

prompt:
  temperature: 1.0
  model: HuggingFaceTB/SmolLM3-3B
  max_headlines: 10

inspirations:
  file: inspirations.txt
  pick_count: 2

sources:
  - reuters
  - foxnews
  - cnn
  - bbc
  - ft
  - npr
  - guardian
  - breitbart
